# Use the official NGINX image from the Docker Hub
FROM nginx:alpine

# Copy the content of the public folder to the NGINX html directory
COPY public /usr/share/nginx/html

# Expose port 80
EXPOSE 80
